spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estoque?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    hostname: localhost
    host: localhost
    port: 5672
    virtualhost: /
    username: guest
    password: guest
  security:
    basic:
      enabled: false
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
